### ISSUE TITLE
That's kinda rude

### ISSUE THREAD

**Issue by MoreSaltMoreLemon** [learn-co-curriculum/Mod-5-Web-Dev-Handbook#2]
Day 5 - Graduation

You made it! Today you get your final survey, a free bagel/muffin/coffee breakfast and you get to take part in the graduation ceremony. Get hype! Graduation will be over by noon, and **you’ll be expected to clear out by 1:00 to make way for a brand new Mod 5 class.**

There's better ways of saying this than tagging it at the end of project specs.

**Comment by maxwellbenton** [comment]
Hi @MoreSaltMoreLemon,

Thank you for spotting this and providing feedback. You're right, and we agree. We've updated this section to more politely explain the request.
